### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by lacabra** [claytonrcarter/cropplanning#12]
Hi Clayton,

Sorry to see this project without maintainer. If you have just 1 minute to spare, I would encourage you to add a LICENSE to this repository to make it easier to transition to someone else. Many developers will pass a repository without a license because it is not clear the terms under which that project is released (even though you explicitly say it's free), and the original owner could always come back and claim rights that were not clear, or enter a legal dispute...

Github makes it really easy to add a license following these [simple steps](https://help.github.com/en/articles/adding-a-license-to-a-repository), where you just create a file with the name `LICENSE` and Github understands you want to add a license to your project and offers you a number of templates with the most common licenses. In broad strokes, if you want the most permissive license, you can choose MIT, and if you care for all redistributions to remain open source, you can choose the slightly more restrictive GPLv3. For some help in choosing a license, you can visit the intuitive and straightforward https://choosealicense.com/

I came across your site while researching [Digital Public Goods](https://digitalpublicgoods.net/candidates/), and I'm planning to add yours to the list, but only after a license has been added. Let me know if you need any further guidance in choosing a license, happy to help.

**Comment by claytonrcarter** [comment]
Thanks for the nudge, Victor. Addressed in 0295da41.
