### ISSUE TITLE
Interested developer

### ISSUE THREAD

**Issue by xeruf** [claytonrcarter/cropplanning#13]
I was originally looking for a software to plan intercropping with the crops I have at hand, with inbuilt support to account for symbioses and bad neighbors. There are myriads of tables for that out there, but why go through them by hand if there can be a handy software?

So as a developer and beginning gardening enthusiast I would like to ask whether such a feature is available here, and indicate interest in further development.

**Comment by claytonrcarter** [comment]
Hi. Thanks for your interest but I'm sorry to say that, no, that is not currently supported and I do not have plans to add such a feature. This project is no longer maintained. Best of luck!
