### ISSUE TITLE
Database not present

### ISSUE THREAD

**Issue by rrleesb** [claytonrcarter/cropplanning#4]
I haven't used crop planning since last season but now when I open it my crop database is no longer there.

I'm using version 0.7

Is there a way to reassociate the previouse database that I had created?

**Comment by rrleesb** [comment]
[ExportedCropsAndVars.zip](https://github.com/claytonrcarter/cropplanning/files/386644/ExportedCropsAndVars.zip)

**Comment by claytonrcarter** [comment]
Sorry for the super-late reply.  Please see the first entry on the [troubleshooting wiki page](https://github.com/claytonrcarter/cropplanning/wiki/ProblemsAndTroubleshooting) for the most common causes of data/db missing.  Please reopen this issue if that doesn't help.
