### ISSUE TITLE
No .exe file in clone/download

### ISSUE THREAD

**Issue by philg1981** [claytonrcarter/cropplanning#5]
Any suggestions?

**Comment by claytonrcarter** [comment]
Phil, sorry for the super-late reply.  The .exe isn't included in the repo (it's built as part of a an Ant built script, as I recall), so you won't get it as part of the clone or download process.  You may have better luck checking out the [releases](https://github.com/claytonrcarter/cropplanning/releases).

**Comment by philg1981** [comment]
Many thanks.
